// Companies
export const GET_COMPANIES_SUCCESS = 'GET_COMPANIES_SUCCESS';
export const CREATE_COMPANY_SUCCESS = 'CREATE_COMPANY_SUCCESS';
export const GET_COMPANY_SUCCESS = 'GET_COMPANY_SUCCESS';
export const UPDATE_COMPANY_SUCCESS = 'UPDATE_COMPANY_SUCCESS';
export const DELETE_COMPANY_SUCCESS = 'DELETE_COMPANY_SUCCESS';

// Pricelists
export const GET_PRICELISTS_SUCCESS = 'GET_PRICELISTS_SUCCESS';
export const EDIT_PRICELIST_SUCCESS = 'EDIT_PRICELIST_SUCCESS';
export const DELETE_PRICELIST_SUCCESS = 'DELETE_PRICELIST_SUCCESS';
export const PRICELIST_INFO_SUCCESS = 'PRICELIST_INFO_SUCCESS';
